### ISSUE TITLE
[cas_pods_setup] No such file or directory: AppMetricaCore.bundle

### ISSUE THREAD

**Issue by krabdog** [cleveradssolutions/CAS-iOS#4]
When running `python cas_pods_setup.py setup --adapters Optimal` the error occurres:
```
## Find Resources
   Resources PAGAdSDK.bundle
   Resources AppMetricaCore.bundle
Traceback (most recent call last):
  File "cas_pods_setup.py", line 376, in <module>
    main()
  File "cas_pods_setup.py", line 361, in main
    find_resources_in_pods()
  File "cas_pods_setup.py", line 219, in find_resources_in_pods
    shutil.move(bundle, bundlePath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 325, in move
    copy2(src, real_dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 153, in copy2
    copyfile(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '${PODS_CONFIGURATION_BUILD_DIR}/AppMetricaCore/AppMetricaCore.bundle'
```

**Comment by Str4tos** [comment]
Thank you for raising this issue! We're pleased to inform you that the problem has been fixed in the 1.5 update.
